# autoreg.ps1
# Scans for C++ headers with the SCRIPT() macro and generates registerScripts.cpp

$ScriptDir = $PSScriptRoot
$OutputFile = "$ScriptDir\registerScripts.cpp"

# Find all .h files in the directory
$Headers = Get-ChildItem -Path $ScriptDir -Filter *.h -Recurse

$FoundScripts = @()

foreach ($file in $Headers) {
    # Speed check: only look for "SCRIPT(" string
    if (Select-String -Path $file.FullName -Pattern "SCRIPT\s*\(") {
        $FoundScripts += $file.Name
    }
}

# Generate the file content
$Content = @"
// ---------------------------------------------------------------------------
// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by autoreg.ps1 during Pre-Build event.
// ---------------------------------------------------------------------------

"@

foreach ($name in $FoundScripts) {
    $Content += "#include `"$name`"`n"
}

$Content += @"

extern "C" __declspec(dllexport) void registerScripts() {
	// Scripts register themselves via the SCRIPT() macro's static initializer.
}
"@

# Write only if changed to avoid unnecessary re-compiles
if (Test-Path $OutputFile) {
    $OldContent = Get-Content $OutputFile -Raw
    if ($OldContent -ne $Content) {
        Set-Content -Path $OutputFile -Value $Content -Encoding UTF8
        Write-Host "Updated $OutputFile with $($FoundScripts.Count) scripts."
    }
} else {
    Set-Content -Path $OutputFile -Value $Content -Encoding UTF8
}
