#pragma once

// ENGINE_API — controls dllexport/dllimport for engine symbols used by script DLLs.
//
// When compiling the engine itself (BUILDING_ENGINE is defined in Vulkan_Engine.vcxproj):
//   Symbols decorated with ENGINE_API are exported from Vulkan_Engine.exe and written
//   into Vulkan_Engine.lib (generated by the /IMPLIB linker option).
//
// When compiling script DLLs (GameScripts, etc.):
//   ENGINE_API becomes __declspec(dllimport), which tells the linker to find those
//   symbols in Vulkan_Engine.lib at compile time and Vulkan_Engine.exe at runtime.

#ifdef _WIN32
  #ifdef BUILDING_ENGINE
    #define ENGINE_API __declspec(dllexport)
  #else
    #define ENGINE_API __declspec(dllimport)
  #endif
  // Disable "needs to have dll-interface to be used by clients of class" warning
  // Safe since we match runtimes and compilers between engine and script DLLs.
  #pragma warning(disable: 4251)


#else
  #define ENGINE_API
#endif
